app:
  name: "ariskaAdi/personal-digital-wallet"
  port: "4000"
  jwt_secret: "dev-secret-123"

db:
  host: "localhost"
  port: 5432
  name: "fiber"
  user: "postgres"
  password: "postgres"
  connection_pool:
    max_idle_connection: 10
    max_open_connection: 30
    max_lifetime_connection: 60 #second
    max_idle_time_connection: 60
